name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: gitkf
        path: build/gitkf.exe